### ISSUE TITLE
Wayland KDE Plasma Supported?

### ISSUE THREAD

**Issue by br6** [azalinux/realvnc-server-aarch64-manjaro#10]
How can I get this to work within Wayland KDE Plasma img of Manjaro on a RPI5 ?

what method is raspberryOS using to make it work via wayland

**Comment by azalinux** [comment]
Hello,

RealVNC Server does NOT support Wayland (as yet).  They have indicated that it is in their roadmap but there is no ETA.

In terms of how RaspberryOS has vnc support, it now uses Wayvnc to provide vnc capabilities.  This isn't RealVNC though - Wayvnc is an open source alternative for wlroots based Wayland compositors.

Note:   KDE plasma is not a wlroots based wayland desktop so wayvnc will not work natively on KDE Plasma!  

The only easy option in KDE wayland at the moment is to install Plasma's native remote desktop client krfb - it supports wayland and should work for vnc access.
