### ISSUE TITLE
VNC can't show desktop unless physical monitor connected

### ISSUE THREAD

**Issue by hogAlert** [azalinux/realvnc-server-aarch64-manjaro#2]
I'm reporting this as an issue in case it helps anyone, even though I've solved it.

Problem:
RealVNC is 'unable to show the desktop' unless a physical monitor is connected (on a Pi 4 4GB, with a fresh install of Manjaro XFCE, although I suspect same for all hardware versions and OS flavours).

Solution:
This can be resolved by adding the following lines to /boot/config.txt (needs root access e.g sudo nano /boot/config.txt)

hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=82

(These lines were taken from the same file on a pi running Raspbian)

**Comment by azalinux** [comment]
I'll leave this pinned as this is a known quirk of the Raspberry Pi hardware interface which causes this to occur & for those extra options needed in the /boot/config.txt file.
