### ISSUE TITLE
I cannot connect

### ISSUE THREAD

**Issue by GreenTeodoro839** [azalinux/realvnc-server-aarch64-manjaro#4]
The computer's IP address couldnot be contacted.
But I can connect my raspberry pi by SSH

**Comment by azalinux** [comment]
hello,
Can you confirm what OS you are using on the Pi ?... I assume manjaro ?  Please type this in a terminal too and let us know what shows:       uname -a

Also please check the following to make sure realvnc is actually running and to see if any errors appear:

$ sudo systemctl status vncserver-x11-serviced

If that shows ok, other common things to check is if you are running a firewall like firewalld , make sure port 5900 is open.

**Comment by GreenTeodoro839** [comment]
> hello, Can you confirm what OS you are using on the Pi ?... I assume manjaro ? Please type this in a terminal too and let us know what shows: uname -a
> 
> Also please check the following to make sure realvnc is actually running and to see if any errors appear:
> 
> $ sudo systemctl status vncserver-x11-serviced
> 
> If that shows ok, other common things to check is if you are running a firewall like firewalld , make sure port 5900 is open.

I run
sudo systemctl stop firewalld
and everything works well
