### ISSUE TITLE
/usr/bin/vncserver-x11-core: error while loading shared libraries: libbcm_host.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by NeoFax75** [azalinux/realvnc-server-aarch64-manjaro#5]
This is the error I get when starting on my RPI4 with the prebuilt package.

**Comment by azalinux** [comment]
Hello,

I just went back and installed a fresh version (22.04) of Manjaro ARM64 Xfce & Mate as a test on my Pi4 and both worked fine with the precomplied package for realvnc server.

I need to know what version of Manjaro you installed on your raspberry Pi and what kernel you are running:

Do this in a terminal to find out the kernel:   $ uname -a

Cheers
Aaron

**Comment by NeoFax75** [comment]
From my OrangePi3-LTS running Manjaro Arm:
Linux OPI3-Manjaro 5.17.6-1-MANJARO-ARM #1 SMP PREEMPT Mon May 9 12:42:34 UTC 2022 aarch64 GNU/Linux

From my RPI4 running Manjaro ARM:
Linux RPI4-Manjaro 5.17.5-1-MANJARO-ARM-RPI #1 SMP PREEMPT Wed May 4 17:30:05 UTC 2022 aarch64 BNU/Linux

Both do not work as it says:
/usr/bin/vncserver-x11: error while loading shared libraries: libbcm_host.so.0: cannot open shared object file: No such file or directory
/usr/bin/vncserver-x11: error while loading shared libraries: libbcm_host.so.0: cannot open shared object file: No such file or directory

**Comment by NeoFax75** [comment]
[SOLVED] 
This package will as far as I have tested work on a RPI 4 system.  You will need to cp over the above mentioned libraries to where Manjaro is expecting them for this to work.  Tomorrow I am going to try and copy these files over onto my OPI3-LTS system and see if they will work.

sudo cp /opt/vc/lib/libbcm_host.so /usr/lib/libbcm_host.so.0
sudo cp /opt/vc/lib/libvcos.so /usr/lib/libvcos.so.0
sudo cp /opt/vc/lib/libvchiq_arm.so /usr/lib/libvchiq_arm.so.0
