### ISSUE TITLE
Authorization error?

### ISSUE THREAD

**Issue by elliot0319** [azalinux/realvnc-server-aarch64-manjaro#7]
I'm trying to run Manjaro on rpi4 with iPad as the display.

When I Check its status, it says active(running), so at least I know that it's running.
But when I tried to access it in my client computer, it would say, "connection refused by the computer."

In the status, it would say, 
vncserver-x11[435]: AgentInitCheck: agent commes failure
vncserver-x11[435]: AgentInitCheck: no response from agent
vncserver-x11[2371]: Authorization required, but no authorization protocol specified
vncserver-x11[2371]: Authorization required, but no authorization protocol specified

I went online to see if I can get any hints, but no..
''Fix the port, you may be using the wrong port or maybe you didn't initiate vnc..." 

Is there anything in the setup process that I missed?

**Comment by azalinux** [comment]
hello,
So just to get your setup confirmed, are you trying to use the Ipad to vnc into the Pi  or using the iPad as a monitor for the PI?

Going by the status error, it sounds the the remote agent is trying to connect but it isn't agreeing (or getting any auth protocols sent to the pi.)    what client are you using to try and connect - is it the proper real vncviewer or 3rd party viewer? 

Make sure you check to make sure it isn't the firewall interfering on the pi or the client.  The port should be 5900 so make sure that is open or temp disable any firewalls to eliminate this as a potential cause.

Also what manjaro kernel version is running on the pi and is it version 6 or 7 of real vnc server running on the pi ?

**Comment by azalinux** [comment]
closing issue as it's been 2 weeks with no response received asking for more info .
