### ISSUE TITLE
Facing installation issue while doing makepkg -si

### ISSUE THREAD

**Issue by Jyo561** [azalinux/realvnc-server-aarch64-manjaro#8]
facing error message:
curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://www.realvnc.com/download/file/vnc.files/VNC-Server-7.0.1-Linux-ARM64.deb
while running makepkg -si

Note: all instructions in readme.md followed

**Comment by azalinux** [comment]
Hello,

Looks like the source DEB file URL has changed upstream - i've updated it in the PKGBUILD so clone the repo again to get the updated PKGBUILD and try again:)

**Comment by Jyo561** [comment]
Thanks a lot I got that part done
But I am facing another issue while running VNC server when I am trying to access it from another device it's not connecting and 
When I ran 
systemctl status vncserver-x11-serviced

It shows 
ConsoleDisplay: Cannot find a running display on vt2

Update:
On gnome it had the above problem

Then I tried it on MATE and I could connect to the VNC but screen was not visible

Update 2: 
Just tried KDE plasma and it works on it but unable to connect to remote system i.e my desktop, shows " computers IP address cannot be connected ".

**Comment by azalinux** [comment]
heya, 
For the record, I have my realvnc release 7.0.1 working on Manjaro (aarch64) running Mate so we know the base package works.

The obvious thing to ask is are you running your Raspberry Pi headless ?  Meaning do you have a monitor plugged into the Hdmi port on the Pi?  If you don't, plug one in for troubleshooting purposes.  

The other thing is make sure you disable any firewall software you have running on the Pi ie Firewalld is common on Manjaro installs so either disable it or make sure port 5900 is open.

More generally speaking especially with Gnome, make sure you login to gnome using Xorg mode and not Wayland mode.   Wayland mode will not work with realvnc.

There is nothing special required from mate or kde plasma - it should work out of the box with realvnc.

Lastly, what type of raspberry pi are you running and what version of manjaro are you running and the kernel version too?

**Comment by Jyo561** [comment]
> heya, 
> For the record, I have my realvnc release 7.0.1 working on Manjaro (aarch64) running Mate so we know the base package works.
> 
> The obvious thing to ask is are you running your Raspberry Pi headless ?  Meaning do you have a monitor plugged into the Hdmi port on the Pi?  If you don't, plug one in for troubleshooting purposes.  
> 
> The other thing is make sure you disable any firewall software you have running on the Pi ie Firewalld is common on Manjaro installs so either disable it or make sure port 5900 is open.
> 
> More generally speaking especially with Gnome, make sure you login to gnome using Xorg mode and not Wayland mode.   Wayland mode will not work with realvnc.
> 
> There is nothing special required from mate or kde plasma - it should work out of the box with realvnc.
> 
> Lastly, what type of raspberry pi are you running and what version of manjaro are you running and the kernel version too?
> 
> 



Ok it finally worked
